### ISSUE TITLE
When Host 5 seconds then it Disconnect 

### ISSUE THREAD

**Issue by hassanajs** [luskaner/ageLANServer#56]
I tried with Internet and with your companion launcher its the same

**Comment by luskaner** [comment]
Hello:

Please attach the latest log residing in `server/logs`

You may also have a look at the other similar issue https://github.com/luskaner/aoe2DELanServer/issues/52 

Make sure you have read https://github.com/luskaner/aoe2DELanServer/wiki/Troubleshooting (and https://github.com/luskaner/aoe2DELanServer/wiki/Questions-and-Answers-(QA))

**Comment by hassanajs** [comment]
[access_log_2024-10-23T10-26-05.txt](https://github.com/user-attachments/files/17486862/access_log_2024-10-23T10-26-05.txt)
I don't have the Issue of #52  , because I can create a lobby but I got disconnected after multiple seconds.

**Comment by luskaner** [comment]
To have some context, there are 2 servers that the client uses, the main server (this is what I provide), and the the Battle Server (you can find it as `BattleServer\BattleServer.exe`) that the game uses for the lobby and the match itself (the game on startup launches it on the background). The Battle Server is pretty much a Black Box that's out of scope for this project.

To make sure it's a Battle Server issue I would:

* Try the official game launcher and see if it happens.
* Try my other older versions, the last of 1.2.x and 1.3.x (to check it's not my server)
* Try hosting the lobby on another PC if possible.
* Provide the game log (inside %USERPROFILE%\Games\Age of Empires 2 DE\logs, the folder with the date and inside the same name).

**Comment by hassanajs** [comment]
[2024.10.23-10.26.50.txt](https://github.com/user-attachments/files/17490613/2024.10.23-10.26.50.txt)
here is the log requested

**Comment by luskaner** [comment]
@hassanajs there is a bunch of errors that are not normally seen with my server:

`ExtensionDoExternalCallEvent - response was failure: 401``(which is not to my server but another unknown service, maybe the Battle Server?)

Plus, the game version you are using is pretty old (more than 7 months) and could have bugs that have been resolved (for obvious reasons I only test with the latest version)`:

```
Build version: 101.102.42346.0 #(107882)
Build stream: release
Build config: Final Steam D3D11, built on PhoenixBuilder-, at 2024-03-13T00:41:21
```

The latest version as of now is:

```
Build version: 101.102.61625.0 #(127161)
Build stream: release_prepaphos
Build config: Final, built on PhoenixBuilder-, at 2024-10-21T15:46:17
```

**Comment by hassanajs** [comment]
Ok then before I update the game , do you suggest any thing to do with battle server before I close the issue or suggest me to try anything?

**Comment by luskaner** [comment]
> To have some context, there are 2 servers that the client uses, the main server (this is what I provide), and the the Battle Server (you can find it as `BattleServer\BattleServer.exe`) that the game uses for the lobby and the match itself (the game on startup launches it on the background). The Battle Server is pretty much a Black Box that's out of scope for this project.
> 
> To make sure it's a Battle Server issue I would:
> 
> * Try the official game launcher and see if it happens.
> * Try my other older versions, the last of 1.2.x and 1.3.x (to check it's not my server)
> * Try hosting the lobby on another PC if possible.
> * Provide the game log (inside %USERPROFILE%\Games\Age of Empires 2 DE\logs, the folder with the date and inside the same name).

The steps I said here (except the logs you already provided), anyway you don't need to close the issue, you can test this (and updating) and tell me if any succeeded

**Comment by victor-cortes** [comment]
Same error here, got disconnected from lobby after about 5 seconds.

I am using:
- AoE2DE_s Version 101.102.42346.0 (#107882) 10
- The latest [Goldberg Emulator](https://github.com/Detanup01/gbe_fork)
- ageLANServerLauncherCompanion (created a folder named dlls containing the dll)

My ColdClientLoader.ini:

```
# modified version of ColdClientLoader originally by Rat431
[SteamClient]
# path to game exe, absolute or relative to the loader
Exe=AoE2DE_s.exe
# empty means the folder of the exe
ExeRunDir=
# any additional args to pass, ex: -dx11, also any args passed to the loader will be passed to the app
ExeCommandLine=
# IMPORTANT, unless [Persistence] Mode=2
AppId=813780

# path to the steamclient dlls, both must be set,
# absolute paths or relative to the loader
SteamClientDll=steamclient.dll
SteamClient64Dll=steamclient64.dll

[Injection]
# force inject steamclient dll instead of waiting for the app to load it
ForceInjectSteamClient=0

# force inject GameOverlayRenderer dll instead of waiting for the app to load it
ForceInjectGameOverlayRenderer=0

# path to a folder containing some dlls to inject into the app upon start, absolute path or relative to this loader
# this folder will be traversed recursively
# additionally, inside this folder you can create a file called `load_order.txt` and
# specify line by line the order of the dlls that have to be injected
# each line should be the relative path of the target dll, relative to the injection folder
# If this file is created then the loader will only inject the .dll files mentioned inside it
# example:
#DllsToInjectFolder=extra_dlls
DllsToInjectFolder=dlls

# don't display an error message when a dll injection fails
IgnoreInjectionError=0
# don't display an error message if the architecture of the loader is different from the app
# this will result in a silent failure if a dll injection didn't succeed
# both the loader and the app must have the same arch for the injection to work
IgnoreLoaderArchDifference=0

[Persistence]
# 0 = turned off
# 1 = loader will spawn the exe and keep hanging in the background until you press "OK"
# 2 = loader will NOT spawn exe, it will just setup the required environemnt and keep hanging in the background
#     you have to run the Exe manually, and finally press "OK" when you've finished playing
#     you have to rename the loader to "steam.exe"
#     it is advised to run the loader as admin in this mode
Mode=0

[Debug]
# don't call `ResumeThread()` on the main thread after spawning the .exe
ResumeByDebugger=0
```
steam_settings/configs.user.ini:

```
[user::general]
# Fill your account name as you would normally see.
account_name=Victor
# Fill with your real steamid or leave empty for it to be auto-generated.
account_steamid=
# Choose one from steam_settings\supported_languages.txt (described in https://partner.steamgames.com/doc/store/localization/languages) or leave empty to be set as 'english'
language=english
# Choose from 'Alpha-2' country code: https://www.iban.com/country-codes or leave empty to be set as 'US'
ip_country=US
```

Game log file:

```
[rlink - error] 2024/11/04 01:15:14.103 (UTC) CallContext::SetComplete - ExtendedError -15 for SetDataAsync. Exception ID .
[rlink - error] 2024/11/04 01:15:14.103 (UTC) SetDataAsync - response was failure: -47 
[rlink - error] 2024/11/04 01:15:14.155 (UTC) WorldwideItemService failed to load offline profile info because signedInventory profileID is invalid or defaultProfileInfo is invalid
[rlink - error] 2024/11/04 01:15:14.155 (UTC) WorldwideAccountService failed to load offline profile info after logging out
[rlink - error] 2024/11/04 01:15:14.641 (UTC) CallContext::SetComplete - ExtendedError -15 for SetDataAsync. Exception ID .
[rlink - error] 2024/11/04 01:15:14.641 (UTC) SetDataAsync - response was failure: -47 
[rlink - error] 2024/11/04 01:15:19.023 (UTC) NetworkManagerInternal waited 5000 ms for async jobs to complete without success
[rlink - error] 2024/11/04 01:15:19.029 (UTC) CallContext::SetComplete - ExtendedError -9 for LogoutAsync. Exception ID .
[rlink - error] 2024/11/04 01:15:19.029 (UTC) LogoutAsync - response was failure: -9 We are not connected
[rlink - error] 2024/11/04 01:15:19.029 (UTC) WorldwideItemService failed to load offline profile info because signedInventory profileID is invalid or defaultProfileInfo is invalid
[rlink - error] 2024/11/04 01:15:19.029 (UTC) WorldwideAccountService failed to load offline profile info after logging out
[rlink - error] 2024/11/04 01:15:19.156 (UTC) CallContext::SetComplete - ExtendedError -15 for SetDataAsync. Exception ID .
[rlink - error] 2024/11/04 01:15:19.156 (UTC) SetDataAsync - response was failure: -47 
[rlink - error] 2024/11/04 01:15:24.025 (UTC) NetworkManagerInternal waited 5002 ms for async jobs to complete without success
[rlink - error] 2024/11/04 01:15:24.071 (UTC) Socks::Free: Socket 0/964 did not close properly before being freed.
[rlink - error] 2024/11/04 01:15:24.072 (UTC) Socks::Free: Socket 0/4212 did not close properly before being freed.
Exiting with code 0
```

What i've already tried:
 - Tried version 1.4.0, 1.3.3 and 1.2.x
 - Tried a different steam emulator

**Comment by luskaner** [comment]
hello @victor-cortes:

You are showing the same outdated version as @hassanajs, if you have done the same troubleshooting as I told him, I very much suspect the game version is at fault here (keep in mind it's 7+ months old at this point). Sometimes, the games breaks the LAN and then fixes it later so the only solution is either to use an older, or newer version (preferred).
