### ISSUE TITLE
client connecting to server kicks other client

### ISSUE THREAD

**Issue by Korozion** [luskaner/ageLANServer#71]
**Describe the bug**
When client2 connects to multiplayer services, client1 is kicked from server (and vice versa)
(With _ServerLauncherCompanion_ and server config.toml with parameter `GeneratePlatformUserId = true`

**To Reproduce**

1. Launch server on machine A
2. Launch client1 on machine B
3. Launch client2 on machine C
4. Client1 gets "sorry, you have lost connection to multiplayer services"

**Expected behavior**
Client1 should not get disconnected

**Games**

Check all that apply:

- Age of Empires II: Definitive Edition

**Server**

- OS and Architecture: Debian 6.1.115-1 x86_64
- Server version : 1.6.0
- Server log : [access_log_2024-11-21T18-13-55.txt](https://github.com/user-attachments/files/17851864/access_log_2024-11-21T18-13-55.txt)

**Client1**

- OS: Windows 10 Enterprise 21H2 x64
- Client version 1.6.0

**Client2**

- OS: Windows 10 Enterprise 21H2 x64
- Client version 1.6.0

**Additional information** 

- Client1 Log : [2024.11.21-18.15.42.txt](https://github.com/user-attachments/files/17851884/2024.11.21-18.15.42.txt)
- Client2 Log : [2024.11.21-18.17.22.txt](https://github.com/user-attachments/files/17851924/2024.11.21-18.17.22.txt)
- Server config.toml with parameter `GeneratePlatformUserId = true`

**Comment by luskaner** [comment]
Hello:

Can you try server versions `1.5.0` and `1.4.0` to confirm it is a bug (and introduced in later versions?

Thanks

**Comment by Korozion** [comment]
Hey !
Ok so I tried those configs :
Server v1.5.0 and clients 1.6.0 -> exact same problem
Server v1.5.0 and clients 1.5.0 -> exact same problem
Server v1.4.0 and clients 1.5.0 -> exact same problem
So I guess something is wrong with my configuration somewhere but I can't find out what...

**Comment by luskaner** [comment]
Mmm it's strange it's like `GeneratePlatformUserId = false` but you say is `true`, I've just tested locally and it works.... so, in the mean time, I suggest you make sure every PC uses a different steam emulator config specially regarding the platform user id (`account_steamid` as explained in my other repo) (when it's set to 0 it's generated in the first launch) so that that option becomes irrelevant :)

**Comment by Korozion** [comment]
That was it ! the generated folders inside %userprofile%\Games\Age of Empires 2 DE\76561197.... were the same number on the 2 clients.
it works now, thank you !
