### ISSUE TITLE
bug create lobby

### ISSUE THREAD

**Issue by skylidefr** [luskaner/ageLANServer#72]
**Describe the bug**
hello, on Aoe2DE. when i'm on the lobby browser and i want to create a lobby. i can't create a lobby because the game can't define if the lobby name is possible or not.
https://imgur.com/yNnGWGc

**Games**

Check all that apply:

- Age of Empires II: Definitive Edition

Server

OS and Architecture: Windows
OS Version and architecture: 11
Server version: 1.6.0
Launcher

OS: Windows
OS Version and architecture [e.g. 11 x64]: 11
Client version [e.g. 1.0.0]: 1.6.0

**Comment by luskaner** [comment]
Hello:

That looks like there might be an issue connecting to the BattleServer you will need to ensure BattleServer.exe is allowed through the firewall (you may test simply disabling the firewall altogether). 
If that's not the issue I will need the server logs (`server/logs`) and the relevant client log (`%userprofile%\Games\Age of Empires 2 DE\logs`) so further examine the issue.
