### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by EsdrubalMagano** [luskaner/ageLANServer#87]
Hey there!

This is not a bug but just a question, I haven actually manged to figure out how is this actually works. 

I have AoE II is 2 computers over the same network with VPN.  I assume that will work the same as the "custom launcher"?

Then what is the process of creating a LAN match?

I run server on the PC that created the lobby and launcher on the other? or both? or just server is fine?

Do I need to also change the config and add the game executable?

Anyway, thank you for this great piece of software!

**Comment by luskaner** [comment]
Hello, glad you like it ;)

* **VPN or real LAN it does not matter**, but depending on the VPN it might be more tricky to "discover" the server. If it is not discovered, make sure "Broadcast" and/or "Multicast" is enabled on the VPN software.
* If you use a custom launcher **every PC will need the config to point to the game launcher exe** (*already explained in the instructions how exactly*)
* The launcher first tries to discover an existing server and, if it cannot detect one, it will execute the server itself. So, by the default, **the first PC that runs the launcher will host the server**.
* Regardless who hosts the server, **anyone can host the lobby** (and that's done via the internal BattleServer.exe)

Hope it answers the doubts :)
