### ISSUE TITLE
Certificate fails on client computers: "aoe-api.worldsedgelink.com must have been trusted automatically at this point." --- Launcher.exe (launcher_aoe2.bat): 

### ISSUE THREAD

**Issue by QueenieArtemisia** [luskaner/ageLANServer#90]
**ℹ️ MAKE SURE YOU HAVE READ [TROUBLESHOOTING](https://github.com/luskaner/ageLANServer/wiki/Troubleshooting)
and [QA](https://github.com/luskaner/ageLANServer/wiki/Questions-and-Answers-(QA)) FIRST.**

**Describe the bug**
After carefully following the setup guides of both this and the offline addon files, launcher_aoe2.bat fails ONLY on computers other than the host.

The flow and eventual error that appears in the console:

"Adding host to hosts file, authorize "config-admin-agent" if needed...
Adding server certificate to local store
aoe-api.worldsedgelink.com must have been trusted automatically at this point.       <------ THIS IS WHERE SOMETHING IS OFF
Cleaning up...
Cleaned up.
Program finished with errors...
You may try running "cleanup-aoe2.bat" as regular user."

- I tried cleaning the certificates myself, it did not help. Even if the certificate is not there in the first place, the same error happens. Hosts do not experience this (the first computer on the LAN to run the launcher). If the first computer stops the server and the second one starts one, it experiences NO problems, but then the first computer runs into this issue.

**To Reproduce**

1. Follow the instructions to install the server with the offline launcher (Goldberg) to the letter
2. Run launcher for AoE2-DE on a computer on an LAN
3. Run launcher on a second computer to attempt to connect to the first one's server

**Expected behavior**

- The error "aoe-api.worldsedgelink.com must have been trusted automatically at this point." should appear in the client computer's console. After that, the console cleans up and closes, never entering the game.

**Software Components**

Check all that apply:

- Launcher
- Launcher configurator   <---- perhaps?

**Games**

Check all that apply:

- Age of Empires II: Definitive Edition

**Additional context**
- The only way I could make the game work with this server is if I bypassed the Launcher entirely. But this caused unexpected behaviour - clients could not see games in the Lobby, but the COULD be invited. Games worked well without problems.
- For this, however, I needed to capture the certificate (taken while launcher was still running, as it deletes it if the console is closed), pre-install the hosts and make the hosts file read-only, and run the offline launcher (Goldberg) manually. I achieved this via a .bat file. This made the Goldberg exe connect to the server automatically, as I bound it to my RadminVPN IP.

PS: I do not think any server logs would help, as nothing goes wrong on its end.
PPS: Also, if I may ask - what does the launcher do exactly? I ask because my Reddit batch solution somehow works but apparently not as intended (or perhaps not as proficiently as it should). Knowing what it does might help, but I reckon if the issue gets fixed with the launcher, it will be equivalent to that.

**Comment by QueenieArtemisia** [comment]
![Scree](https://github.com/user-attachments/assets/b4bc90fd-ed65-47e5-bf8e-19a22f4dfedc)

**Comment by QueenieArtemisia** [comment]
![Ser](https://github.com/user-attachments/assets/c17a643f-dc3b-4060-a6eb-3adc3543a300)

**Comment by luskaner** [comment]
Hello, while I tackle the main issue, which to be honest, is weird in that it only happens on other PC's and not the server:

> clients could not see games in the Lobby, but the COULD be invited

I know it's a stupid question but... have you made sure the lobby is set to public when creating it?

**Comment by luskaner** [comment]
Also what the launcher does is described in https://github.com/luskaner/ageLANServer/tree/main/launcher#features plus it also tries to fix an issue with the match server (BattleServer.exe) that makes some games not detect the match server and thus enable to join/host matches at all

**Comment by luskaner** [comment]
The certificate check being trusted is done via the `curl` executable, can you ensure both PC's show the same running `curl --version` in PowerShell/CMD such:

```
PS C:\Users\luska> curl --version
curl 8.9.1 (Windows) libcurl/8.9.1 Schannel zlib/1.3 WinIDN
Release-Date: 2024-07-31
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
```

thanks.

**Comment by QueenieArtemisia** [comment]
> Hello, while I tackle the main issue, which to be honest, is weird in that it only happens on other PC's and not the server:
> 
> > clients could not see games in the Lobby, but the COULD be invited
> 
> I know it's a stupid question but... have you made sure the lobby is set to public when creating it?

Yes, the game is public, of course. That was the first thing I checked. I even tried it private to make sure it was not implemented upside-down.






> The certificate check being trusted is done via the `curl` executable, can you ensure both PC's show the same running `curl --version` in PowerShell/CMD such:
> 
> ```
> PS C:\Users\luska> curl --version
> curl 8.9.1 (Windows) libcurl/8.9.1 Schannel zlib/1.3 WinIDN
> Release-Date: 2024-07-31
> Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
> Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
> ```
> 
> thanks.

You were actually correct, the curl versions were different on both PCs somehow, so I updated both of them to the latest version.

Now, however, even the HOST computer has that issue. I can no longer use the launcher at all. Certification fails with the error above.

**Comment by luskaner** [comment]
Hello:

Let's forget the lobby visibility issue until the main issue is fixed as might be related as you said before. So my suspicion with `curl` is the following:

* Windows 10+ (1803 or later) already include the `curl` binary but **it is compiled to use SChannel backend instead of OpenSSL-based thus using the system certificate store**.
* If you download `curl` binary from other sources - including the official page - **it is likely compiled to use the OpenSSL-based backend which does not use the system certificate store *by default***.

Just to confirm my suspicion and do the necessary fix (just use curl under `C:\windows\System32` not the first on the path) can you compare if running these command are different?

`C:\windows\System32\curl.exe --version` and `curl.exe --version` (CMD)

**Comment by QueenieArtemisia** [comment]
Also, this happens if I pre-install the captured certificate.

![Screen3 - Copy](https://github.com/user-attachments/assets/96373258-14b3-4d0c-b4dd-16a0de277891)

**Comment by luskaner** [comment]
Hello:

That's weird, either `mingw` is replacing the windows built-in `curl` (which I doubt) or you are using an old version of Windows 10? What version are you on?

You can simply run `ver` on CMD such:

```
C:\Users\luska>ver

Microsoft Windows [Versión 10.0.26100.2033]
```

**Comment by QueenieArtemisia** [comment]
Microsoft Windows [Version 10.0.19045.2965]

----------------------------------------------------

This was the curl version before I updated it (I backed it up in case you asked for it).

C:\Windows\System32>curl --version
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

----------------------------------------------------

The current curl version is the latest: v8.11


----------------------------------------------------

What version of curl are you on that makes everything work?

**Comment by luskaner** [comment]
Your windows version (please check both PC's) is fine, the minimum version supported is `10.0.17763`.
The original version of `curl` you had is the one windows comes with and that's what my app needs to work properly, please restore it on both PC's.
After you've done all of that, please test this [updated launcher](https://github.com/user-attachments/files/18187445/aoe2DELanServer_launcher_1.6.3_win_x86-64.zip) which makes sure the `curl.exe` used is the one from `C:\Windows\System32` folder.

**Comment by QueenieArtemisia** [comment]
- Reverted both PCs to curl v8.0.1

- Server host PC has no issue

- Client PC receives same error:

`Adding server certificate to local store
aoe-api.worldsedgelink.com must have been trusted automatically at this point.`

-------------------------

If PC1 is the host, PC2 has this error.
If PC2 is the host, PC1 has this error.

-------------------------

Let me know if I can help some more in any way.

**Comment by luskaner** [comment]
Hello:

The launcher can be configured to not add hosts or certificates (even run custom bat scripts) **but it will still check if both are correct and that will still fail like now** that's why I want to get to the root of the issue. It's interesting that it only occurs to the one not hosting the web server.

Anyway, while we continue investigating, [here's](https://github.com/user-attachments/files/18189664/aoe2DELanServer_launcher_1.6.3_win_x86-64.zip) a special build of the launcher that after adding the certificate it will not do post-checks so it should work hopefully ;)

**Comment by QueenieArtemisia** [comment]
AWESOME, this fixed the main issue. 

- Now both PCs successfully connect to the server and can enter the Lobby Browser.

- Now there was the other smaller issue: even though firewall options are set correctly, client PCs cannot see hosted LAN games in the Lobby Browser - they can only be invited to games (which works as intended).

- This means that there was NO connection difference between my Reddit workaround and your Launcher fix of now - they both work well when the INVITE option is used but not in the Lobby Browser.

---------------------------

Also, would you consider releasing a version of the launcher that DOES NOT add the necessary line to the "hosts" file? Some people, like me, keep that file read-only, and this launcher simply fails if that is the case. You could notify people in the console that the IP redirect line was not added and needs to be done manually, but the Launcher should not fail, as that is what people use to enter the game. You could make a separate EXE/BAT to handle the certificates/hosts, and the launcher only to connect/resolve network issues. You could tell people to run your setup EXE/BAT first, and then when that is done, simply use the Launcher. This would be EXTRAORDINARY, because if something goes wrong, you'll know it was in the setup step, not the networking step of the game launcher. 

---------------------------

Thank you again for the great work!

**Comment by luskaner** [comment]
Hello:

The launcher already allows to disable the configuration of hosts and/or certificate; have a look at the `resources/config.toml` file and experiment a bit. However, as I said, the check that the host and cert are correctly configured still remains regardless and I think it's a good idea to keep it.

By the way, the launcher would show different errors than what you see if it was not able to modify the hosts file or add the certificate.

Considering the above I don't agree with having different executables to configure it, nevertheless, an advanced user like you can do it and, as said, the launcher can also be configured, per game, to run an external bat/exe to configure/de-configure if you wanted to.

So... even if we jump over the check the lobby issue still remain. So **I want to keep having a look at why the cert check fails, it might have something to do with the VPN as the fact that it only works for the server, which means connecting to localhost and thus bypassing the VPN completely hints at that**.

After that, we will look into the lobby issue which might be related to that issue or not.

**Comment by luskaner** [comment]
What I want you to do is the following:

1. Run the server manually on PC1.
2. Configure the host mapping manually on PC2 (remember to do `ipconfig /flushdns` afterwards).
3. Configure the certificate manually on PC2.
4. Run `C:\windows\system32\curl.exe -f -s -4 https://aoe-api.worldsedgelink.com && echo %errorlevel%` in cmd.exe on PC2 telling my the number - exit code (it's what the launcher does).

**Comment by QueenieArtemisia** [comment]
1. Ran server on PC1
2. Added server's IP to hosts
3. Added the captured certificate manually
4. Ran your command and got no error (Screenshot below)

Sorry for the delay, just got off a massive work shift. Let me know if I can assist with anything else.

![CMD - Copy](https://github.com/user-attachments/assets/73e912c8-3ef9-44f5-86b8-a9b064d210db)

**Comment by luskaner** [comment]
Hello:

Wrong command sorry, it must be with a single amphersand:

``C:\windows\system32\curl.exe -f -s -4 https://aoe-api.worldsedgelink.com & echo %errorlevel%``

**Comment by QueenieArtemisia** [comment]
Yeah, thinking in Batch does that to a guy. I also didn't notice.

The error code is 0.

![Scr4 - Copy](https://github.com/user-attachments/assets/dd998354-cd00-4304-8d42-cae7f0620f1c)

**Comment by luskaner** [comment]
Yeah I get different results, looks like different curl versions behave different even if they come builtin in Windows, I will remove the use of external curl altogether and do it natively in code so it is consistent. I will attach a special build for testing when done ;)

**Comment by QueenieArtemisia** [comment]
- It works without issues (see screenshot below) - just tested with both PCs.
- Games can only be joined via invites.

- Another question. While testing, I noticed that the certificate being added is only valid until 16 December 2025. This means that true offline is only available for 1 year tops (reliant on connecting to the AoE2 Servers at least once per year to snatch a new certificate). Can something be done about that, to make it available indefinitely, or until 2099 (the maximum of Windows 10)? 

Launcher Console:
![scr5 - Copy](https://github.com/user-attachments/assets/9bf51593-9d6a-469d-9526-9397f5a339a6)

Certificate:
![scr6 - Copy](https://github.com/user-attachments/assets/2c457b87-395c-47e8-8f90-61a704a6eee5)

**Comment by luskaner** [comment]
Hello:

Good that the main issue is finally fixed. To be honest, the generated expiry is 1 year relative to current date for no good reason and it can be generated again by running server/bin/genCert.exe -f, unless you want to have the cert installed permanently (which I do not recommend) is fine right? But I guess extending the expiry would not hurt either.... mmm

**Comment by QueenieArtemisia** [comment]
Well, if it is not too much work and you take such requests, it would help a TON. You know why? Because people like me could compound all of this into a batch solution and the setup could be permanent and instantaneous. 

But you have already worked a lot and helped with the preservation of the game, so I will most certainly not pressure you. 

If you feel like doing this, whenever, it will, of course, be extremely appreciated.

Thank you for everything.

**Comment by luskaner** [comment]
Hello:
No problem, that was my intention for AoE to live forever <3.
Perfect that you found a solution :D
I'll close now this issue (the fix will be included in the next release) if you want me to have a look at the lobby visibility create a new issue with the server logs ;)
